/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminOverviewRouteImport } from './routes/admin.overview'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as PartnerAddProductRouteImport } from './routes/partner.add-product'
import { Route as PartnerProductsRouteImport } from './routes/partner.products'
import { Route as PartnerProfileRouteImport } from './routes/partner.profile'
import { Route as PartnerStockRouteImport } from './routes/partner.stock'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesIdRouteImport } from './routes/services.$id'
import { Route as StoreVendorIdRouteImport } from './routes/store.$vendorId'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as VendorCommissionsRouteImport } from './routes/vendor.commissions'
import { Route as VendorEarningsRouteImport } from './routes/vendor.earnings'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as VendorPartnersRouteImport } from './routes/vendor.partners'
import { Route as VendorSettingsRouteImport } from './routes/vendor.settings'
import { Route as AdminVendorsVendorIdRouteImport } from './routes/admin.vendors_.$vendorId'
import { Route as VendorProductsIndexRouteImport } from './routes/vendor.products.index'
import { Route as VendorProductsNewRouteImport } from './routes/vendor.products.new'
import { Route as VendorProductsIdEditRouteImport } from './routes/vendor.products.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/partner/',
  path: '/partner/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerAddProductRoute = PartnerAddProductRouteImport.update({
  id: '/partner/add-product',
  path: '/partner/add-product',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerProductsRoute = PartnerProductsRouteImport.update({
  id: '/partner/products',
  path: '/partner/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerProfileRoute = PartnerProfileRouteImport.update({
  id: '/partner/profile',
  path: '/partner/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerStockRoute = PartnerStockRouteImport.update({
  id: '/partner/stock',
  path: '/partner/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreVendorIdRoute = StoreVendorIdRouteImport.update({
  id: '/store/$vendorId',
  path: '/store/$vendorId',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const VendorCommissionsRoute = VendorCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => VendorRoute,
} as any)
const VendorEarningsRoute = VendorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => VendorRoute,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => VendorRoute,
} as any)
const VendorPartnersRoute = VendorPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => VendorRoute,
} as any)
const VendorSettingsRoute = VendorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => VendorRoute,
} as any)
const AdminVendorsVendorIdRoute = AdminVendorsVendorIdRouteImport.update({
  id: '/vendors_/$vendorId',
  path: '/vendors/$vendorId',
  getParentRoute: () => AdminRoute,
} as any)
const VendorProductsIndexRoute = VendorProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProductsNewRoute = VendorProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProductsIdEditRoute = VendorProductsIdEditRouteImport.update({
  id: '/products/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => VendorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/orders': typeof OrdersRoute
  '/track-order': typeof TrackOrderRoute
  '/vendor': typeof VendorRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/partner/add-product': typeof PartnerAddProductRoute
  '/partner/products': typeof PartnerProductsRoute
  '/partner/profile': typeof PartnerProfileRoute
  '/partner/stock': typeof PartnerStockRoute
  '/products/$id': typeof ProductsIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/store/$vendorId': typeof StoreVendorIdRoute
  '/vendor/commissions': typeof VendorCommissionsRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/partners': typeof VendorPartnersRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/admin/vendors/$vendorId': typeof AdminVendorsVendorIdRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/vendor/products/': typeof VendorProductsIndexRoute
  '/vendor/products/$id/edit': typeof VendorProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/orders': typeof OrdersRoute
  '/track-order': typeof TrackOrderRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/partner/add-product': typeof PartnerAddProductRoute
  '/partner/products': typeof PartnerProductsRoute
  '/partner/profile': typeof PartnerProfileRoute
  '/partner/stock': typeof PartnerStockRoute
  '/products/$id': typeof ProductsIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/store/$vendorId': typeof StoreVendorIdRoute
  '/vendor/commissions': typeof VendorCommissionsRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/partners': typeof VendorPartnersRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/products': typeof ProductsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/admin/vendors/$vendorId': typeof AdminVendorsVendorIdRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/vendor/products': typeof VendorProductsIndexRoute
  '/vendor/products/$id/edit': typeof VendorProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/orders': typeof OrdersRoute
  '/track-order': typeof TrackOrderRoute
  '/vendor': typeof VendorRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/partner/add-product': typeof PartnerAddProductRoute
  '/partner/products': typeof PartnerProductsRoute
  '/partner/profile': typeof PartnerProfileRoute
  '/partner/stock': typeof PartnerStockRoute
  '/products/$id': typeof ProductsIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/store/$vendorId': typeof StoreVendorIdRoute
  '/vendor/commissions': typeof VendorCommissionsRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/partners': typeof VendorPartnersRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/admin/vendors_/$vendorId': typeof AdminVendorsVendorIdRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/vendor/products/': typeof VendorProductsIndexRoute
  '/vendor/products/$id/edit': typeof VendorProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/order-confirmation'
    | '/orders'
    | '/track-order'
    | '/vendor'
    | '/admin/categories'
    | '/admin/commissions'
    | '/admin/orders'
    | '/admin/overview'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vendors'
    | '/partner/add-product'
    | '/partner/products'
    | '/partner/profile'
    | '/partner/stock'
    | '/products/$id'
    | '/services/$id'
    | '/store/$vendorId'
    | '/vendor/commissions'
    | '/vendor/earnings'
    | '/vendor/orders'
    | '/vendor/partners'
    | '/vendor/settings'
    | '/admin/'
    | '/partner/'
    | '/products/'
    | '/services/'
    | '/vendor/'
    | '/admin/vendors/$vendorId'
    | '/vendor/products/new'
    | '/vendor/products/'
    | '/vendor/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/order-confirmation'
    | '/orders'
    | '/track-order'
    | '/admin/categories'
    | '/admin/commissions'
    | '/admin/orders'
    | '/admin/overview'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vendors'
    | '/partner/add-product'
    | '/partner/products'
    | '/partner/profile'
    | '/partner/stock'
    | '/products/$id'
    | '/services/$id'
    | '/store/$vendorId'
    | '/vendor/commissions'
    | '/vendor/earnings'
    | '/vendor/orders'
    | '/vendor/partners'
    | '/vendor/settings'
    | '/admin'
    | '/partner'
    | '/products'
    | '/services'
    | '/vendor'
    | '/admin/vendors/$vendorId'
    | '/vendor/products/new'
    | '/vendor/products'
    | '/vendor/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/order-confirmation'
    | '/orders'
    | '/track-order'
    | '/vendor'
    | '/admin/categories'
    | '/admin/commissions'
    | '/admin/orders'
    | '/admin/overview'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vendors'
    | '/partner/add-product'
    | '/partner/products'
    | '/partner/profile'
    | '/partner/stock'
    | '/products/$id'
    | '/services/$id'
    | '/store/$vendorId'
    | '/vendor/commissions'
    | '/vendor/earnings'
    | '/vendor/orders'
    | '/vendor/partners'
    | '/vendor/settings'
    | '/admin/'
    | '/partner/'
    | '/products/'
    | '/services/'
    | '/vendor/'
    | '/admin/vendors_/$vendorId'
    | '/vendor/products/new'
    | '/vendor/products/'
    | '/vendor/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  OrdersRoute: typeof OrdersRoute
  TrackOrderRoute: typeof TrackOrderRoute
  VendorRoute: typeof VendorRouteWithChildren
  PartnerAddProductRoute: typeof PartnerAddProductRoute
  PartnerProductsRoute: typeof PartnerProductsRoute
  PartnerProfileRoute: typeof PartnerProfileRoute
  PartnerStockRoute: typeof PartnerStockRoute
  ProductsIdRoute: typeof ProductsIdRoute
  ServicesIdRoute: typeof ServicesIdRoute
  StoreVendorIdRoute: typeof StoreVendorIdRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/partner/': {
      id: '/partner/'
      path: '/partner'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/add-product': {
      id: '/partner/add-product'
      path: '/partner/add-product'
      fullPath: '/partner/add-product'
      preLoaderRoute: typeof PartnerAddProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/products': {
      id: '/partner/products'
      path: '/partner/products'
      fullPath: '/partner/products'
      preLoaderRoute: typeof PartnerProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/profile': {
      id: '/partner/profile'
      path: '/partner/profile'
      fullPath: '/partner/profile'
      preLoaderRoute: typeof PartnerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/stock': {
      id: '/partner/stock'
      path: '/partner/stock'
      fullPath: '/partner/stock'
      preLoaderRoute: typeof PartnerStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$vendorId': {
      id: '/store/$vendorId'
      path: '/store/$vendorId'
      fullPath: '/store/$vendorId'
      preLoaderRoute: typeof StoreVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/commissions': {
      id: '/vendor/commissions'
      path: '/commissions'
      fullPath: '/vendor/commissions'
      preLoaderRoute: typeof VendorCommissionsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/earnings': {
      id: '/vendor/earnings'
      path: '/earnings'
      fullPath: '/vendor/earnings'
      preLoaderRoute: typeof VendorEarningsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/partners': {
      id: '/vendor/partners'
      path: '/partners'
      fullPath: '/vendor/partners'
      preLoaderRoute: typeof VendorPartnersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/settings': {
      id: '/vendor/settings'
      path: '/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof VendorSettingsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/admin/vendors_/$vendorId': {
      id: '/admin/vendors_/$vendorId'
      path: '/vendors/$vendorId'
      fullPath: '/admin/vendors/$vendorId'
      preLoaderRoute: typeof AdminVendorsVendorIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/products/': {
      id: '/vendor/products/'
      path: '/products'
      fullPath: '/vendor/products/'
      preLoaderRoute: typeof VendorProductsIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/products/new': {
      id: '/vendor/products/new'
      path: '/products/new'
      fullPath: '/vendor/products/new'
      preLoaderRoute: typeof VendorProductsNewRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/products/$id/edit': {
      id: '/vendor/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/vendor/products/$id/edit'
      preLoaderRoute: typeof VendorProductsIdEditRouteImport
      parentRoute: typeof VendorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminVendorsVendorIdRoute: typeof AdminVendorsVendorIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminVendorsVendorIdRoute: AdminVendorsVendorIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface VendorRouteChildren {
  VendorCommissionsRoute: typeof VendorCommissionsRoute
  VendorEarningsRoute: typeof VendorEarningsRoute
  VendorOrdersRoute: typeof VendorOrdersRoute
  VendorPartnersRoute: typeof VendorPartnersRoute
  VendorSettingsRoute: typeof VendorSettingsRoute
  VendorIndexRoute: typeof VendorIndexRoute
  VendorProductsNewRoute: typeof VendorProductsNewRoute
  VendorProductsIndexRoute: typeof VendorProductsIndexRoute
  VendorProductsIdEditRoute: typeof VendorProductsIdEditRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorCommissionsRoute: VendorCommissionsRoute,
  VendorEarningsRoute: VendorEarningsRoute,
  VendorOrdersRoute: VendorOrdersRoute,
  VendorPartnersRoute: VendorPartnersRoute,
  VendorSettingsRoute: VendorSettingsRoute,
  VendorIndexRoute: VendorIndexRoute,
  VendorProductsNewRoute: VendorProductsNewRoute,
  VendorProductsIndexRoute: VendorProductsIndexRoute,
  VendorProductsIdEditRoute: VendorProductsIdEditRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  OrdersRoute: OrdersRoute,
  TrackOrderRoute: TrackOrderRoute,
  VendorRoute: VendorRouteWithChildren,
  PartnerAddProductRoute: PartnerAddProductRoute,
  PartnerProductsRoute: PartnerProductsRoute,
  PartnerProfileRoute: PartnerProfileRoute,
  PartnerStockRoute: PartnerStockRoute,
  ProductsIdRoute: ProductsIdRoute,
  ServicesIdRoute: ServicesIdRoute,
  StoreVendorIdRoute: StoreVendorIdRoute,
  PartnerIndexRoute: PartnerIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
